# Generated by Django 3.1.7 on 2021-03-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210317_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountGallons', models.IntegerField(blank=True)),
                ('pricePerGallons', models.IntegerField(blank=True)),
                ('dateOfQuote', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
