# Generated by Django 3.0.5 on 2021-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210402_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelquote',
            name='dateOfQuote',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
