# Generated by Django 3.1.7 on 2021-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fuelquote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelquote',
            old_name='amountGallons',
            new_name='gallonsRequested',
        ),
        migrations.RenameField(
            model_name='fuelquote',
            old_name='pricePerGallons',
            new_name='pricePerGallon',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
