# Generated by Django 3.1.7 on 2021-03-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210319_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelquote',
            name='address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='dateRequested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelquote',
            name='quotePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelquote',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fuelquote',
            name='pricePerGallon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
